---
jenkins_version: "2.196"
jenkins_pkg_url: "https://pkg.jenkins.io/redhat"
jenkins_updates_url: "https://updates.jenkins.io"

jenkins_connection_delay: 3
jenkins_connection_retries: 120
jenkins_connection_timeout: 30

jenkins_home: /var/lib/jenkins
jenkins_init_d_dir: "{{ jenkins_home }}/init.groovy.d"

jenkins_hostname: "{{ ansible_default_ipv4.address }}"
jenkins_http_port: 8080
jenkins_https_port: 8443
jenkins_url_prefix: ''
jenkins_url: "https://{{ jenkins_hostname }}:{{ jenkins_https_port }}{{ jenkins_url_prefix }}/"

jenkins_color_theme: null

jenkins_casc_config_path: "{{ jenkins_home }}/jcasc"

jenkins_rebuild_war: false

jenkins_casc_global_config_path: "configuration/global/jcasc"
jenkins_casc_user_config_path: "configuration/hosts/{{ ansible_hostname }}/jcasc"
jenkins_casc_config_files_match: ".*.yml$"

jenkins_email: "CICD Services Jenkins <cicd-services@localhost>"

jenkins_keystore_location: "/usr/lib/jenkins/jenkins-server-certs.keytool"
jenkins_keystore_password: "{{ lookup('password', 'credentials/'+ jenkins_hostname +'/jenkins_keystore_password chars=ascii_letters,digits,hexdigits length=16') }}"

jenkins_java_cmd: /etc/alternatives/java
___jenkins_memory: "{{ (ansible_memtotal_mb * 0.5)|int|abs }}m"
jenkins_java_memory_options: "-Xmx{{ ___jenkins_memory }} -Xms{{ ___jenkins_memory }}"
jenkins_java_jmx_options: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=12345 -Dcom.sun.management.jmxremote.rmi.port=12346 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
jenkins_java_network_options: -Dnetworkaddress.cache.ttl=1 -Dnetworkaddress.cache.negative.ttl=0 -Djava.net.preferIPv4Stack=true
jenkins_java_ssl_options: -Djavax.net.ssl.trustStore=/etc/pki/ca-trust/extracted/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -Djdk.tls.allowUnsafeServerCertChange=true -Dsun.security.ssl.allowUnsafeRenegotiation=true -Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true -Djdk.tls.trustNameService=true
jenkins_java_gc_options: "-XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC -XX:+ScavengeBeforeFullGC -XX:MaxGCPauseMillis=100 -XX:ParallelGCThreads={{ ansible_processor_vcpus }}"
jenkins_other_options: "-Dcasc.jenkins.config={{ jenkins_casc_config_path }} -Djenkins.InitReactorRunner.concurrency={{ ansible_processor_vcpus * 8 | int }}"
jenkins_java_debug: "-Djavax.net.debug=false"
# -Djava.util.logging.config.file=/usr/lib/jenkins/logging.properties
jenkins_java_options: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dpermissive-script-security.enabled=true -Dserver.use-forward-headers=true"

jenkins_proxy_host: null
jenkins_proxy_port: null
jenkins_proxy_user: null
jenkins_proxy_pass: null
jenkins_proxy_exceptions: "metadata.google.internal,{{ jenkins_hostname }}"

jenkins_plugins: {}
jenkins_global_plugins: {}
_jenkins_global_plugins:
  locale: latest
  job-dsl: latest
  configuration-as-code: latest
  configuration-as-code-support: latest
  configuration-as-code-groovy: latest
  timestamper: latest
  ansicolor: latest
  matrix-auth: latest
  script-security: latest
  authorize-project: latest
  ssh-credentials: latest
  git: latest
  matrix-project: latest
  plain-credentials: latest
  command-launcher: latest
  extra-columns: latest
  simple-theme-plugin: latest
  config-file-provider: latest
  credentials: latest
  ssh-agent: latest
  run-condition: latest
  ws-cleanup: latest
  conditional-buildstep: latest
  groovy: latest
  antisamy-markup-formatter: latest
  permissive-script-security: latest
  email-ext: latest
  python: latest
  mask-passwords: latest
  git-client: latest
  nested-view: latest
  build-user-vars-plugin: latest
  multiple-scms: latest
  role-strategy: latest
  progress-bar-column-plugin: latest
  skip-certificate-check: latest

jenkins_process_user: jenkins
jenkins_process_group: jenkins

jenkins_init_file: /etc/sysconfig/jenkins

__jenkins_java_options: "{{ jenkins_java_options }} {{ jenkins_java_memory_options }} {{ jenkins_java_jmx_options }} {{ jenkins_java_network_options }} {{ jenkins_java_gc_options }} {{ jenkins_java_ssl_options }} {{ jenkins_other_options }} {{ jenkins_java_debug }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"

  - option: "JENKINS_HOME"
    value: "{{ jenkins_home }}"

  - option: "JENKINS_PORT"
    value: "{{ jenkins_http_port }}"

  - option: "JENKINS_USER"
    value: "{{ jenkins_process_user }}"

  - option: "JENKINS_JAVA_OPTIONS"
    value: "{{ __jenkins_java_options }}"

  - option: "JENKINS_JAVA_CMD"
    value: "{{ jenkins_java_cmd }}"

  - option: "JENKINS_ENABLE_ACCESS_LOG"
    value: "yes"

  - option: "JENKINS_DEBUG_LEVEL"
    value: "9"
