---
jenkins:
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - name: "adminGlobalRole"
          assignments:
            - admin
          pattern: ".*"
          permissions:
          - "Overall/Administer"
