---
jenkins:
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - name: "anonymous"
          assignments:
            - anonymous
          pattern: ".*"
          permissions:
          - "Overall/Read"
          - "Job/Read"
          - "View/Read"
